# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.4.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-5.4.0-0.1.14.zip
